[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.1", features = [] }

[dependencies]
log = "0.4"
tauri = { version = "2.11.1", features = [] }
tauri-plugin-log = "2"

# "smtp" を追加し、今後の送信処理に備えます
email = { package = "email-lib", version = "0.27.0", features = ["imap", "smtp", "derive"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
toml = "0.8" # TOMLパース用に明示的に追加
tokio = { version = "1", features = ["full"] }
